import Head from "next/head";
import SkillBox from "../components/skills";
import {
  DiscordIcon,
  GithubIcon,
  LinkedInIcon,
  EmailIcon,
  PlusIcon,
  DevIcon,
  SchoolIcon,
  JavascriptIcon,
  TypescriptIcon,
  HtmlIcon,
  CssIcon,
  PythonIcon,
  CIcon,
  CPlusPlusIcon,
  GoIcon,
  RustIcon,
  SqlIcon,
  ReactIcon,
  NextJsIcon,
  TailwindIcon,
  MySqlIcon,
  PostgresIcon,
  Neo4jIcon,
} from "../components/icons";
import Project from "~/components/project";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center bg-[#E0D7C5] px-32 pb-32">
        <ul className="fixed left-0 top-0 z-20 flex min-h-screen flex-col items-center justify-end gap-6 border-r border-black px-3 py-8 text-2xl">
          <li
            key="Github"
            className="flex h-8 w-8 cursor-pointer items-center justify-center hover:text-3xl hover:drop-shadow-sm"
          >
            <a href="https://github.com/oweenen" target="_blank">
              <GithubIcon />
            </a>
          </li>
          <li
            key="LinkedIn"
            className="flex h-8 w-8 cursor-pointer items-center justify-center hover:text-3xl hover:drop-shadow-sm"
          >
            <LinkedInIcon />
          </li>
          <li
            key="Discord"
            className="flex h-8 w-8 cursor-pointer items-center justify-center hover:text-3xl hover:drop-shadow-sm"
          >
            <DiscordIcon />
          </li>
          <li
            key="Email"
            className="flex h-8 w-8 cursor-pointer items-center justify-center hover:text-3xl hover:drop-shadow-sm"
          >
            <EmailIcon />
          </li>
        </ul>
        <div className="fixed top-0 z-10 flex w-full flex-row items-center justify-end gap-12 border-b border-black bg-inherit px-12 py-2 text-2xl font-light">
          <span className="cursor-pointer hover:text-[#4A4A4A]">About</span>
          <span className="cursor-pointer hover:text-[#4A4A4A]">Skills</span>
          <span className="cursor-pointer hover:text-[#4A4A4A]">Projects</span>
          <span className="cursor-pointer hover:text-[#4A4A4A]">
            Experience
          </span>
        </div>
        <a
          className="fixed bottom-0 right-0 mx-4 my-2 cursor-pointer underline hover:text-[#4A4A4A]"
          href="https://github.com/oweenen/portfolio"
          target="_blank"
        >
          Source Code
        </a>
        <div className="flex min-h-screen w-full max-w-5xl flex-col items-start justify-center gap-8 py-32">
          <span className="whitespace-nowrap text-5xl font-bold">
            Hi, I'm Owen
          </span>
          <div className="relative h-0">
            <PlusIcon className="absolute bottom-[-20px] left-[-35px] text-4xl" />
          </div>
          <span className="text-3xl">
            University Student <SchoolIcon className="inline" />
          </span>
          <p className="max-w-xs">
            I am currently in my junior year at The University of Massachusetts
            Lowell studying Computer Science with a focus on Data Science.
          </p>
          <span className="text-3xl">
            Web Developer <DevIcon className="inline" />
          </span>
          <p className="max-w-xs">
            I build full stack web applications about things I find interesting.
          </p>
        </div>
        <div className="flex w-full max-w-5xl flex-row flex-wrap gap-8">
          <SkillBox
            label="Languages"
            skillProps={[
              { id: "javascript", icon: JavascriptIcon },
              { id: "typescript", icon: TypescriptIcon },
              { id: "html", icon: HtmlIcon },
              { id: "css", icon: CssIcon },
              { id: "python", icon: PythonIcon },
              { id: "c", icon: CIcon },
              { id: "cplusplus", icon: CPlusPlusIcon },
              { id: "go", icon: GoIcon },
              { id: "rust", icon: RustIcon },
              { id: "sql", icon: SqlIcon },
            ]}
          />
          <SkillBox
            label="Frameworks"
            skillProps={[
              { id: "react", icon: ReactIcon },
              { id: "nextjs", icon: NextJsIcon },
              { id: "tailwind", icon: TailwindIcon },
            ]}
          />
          <SkillBox
            label="Databases"
            skillProps={[
              { id: "mysql", icon: MySqlIcon },
              { id: "postgres", icon: PostgresIcon },
              { id: "neo4j", icon: Neo4jIcon },
            ]}
          />
        </div>
        <div className="flex w-full max-w-5xl flex-col gap-8 py-8">
          <Project />
        </div>
      </main>
    </>
  );
}
