import Head from "next/head";
import {
  DiscordIcon,
  GithubIcon,
  LinkedInIcon,
  EmailIcon,
  PlusIcon,
  DevIcon,
  SchoolIcon,
  JavascriptIcon,
  TypescriptIcon,
  HtmlIcon,
  CssIcon,
  PythonIcon,
  CIcon,
  CPlusPlusIcon,
  GoIcon,
  RustIcon,
  SqlIcon,
} from "../components/icons";

type SkillProps = {
  id: string;
  icon: React.FC<React.SVGProps<SVGSVGElement>>;
};

const Skill = ({ id, icon: Icon }: SkillProps): JSX.Element => {
  return (
    <div className="flex h-12 w-12 items-center justify-center text-[40px] hover:text-5xl hover:drop-shadow-lg">
      <Icon />
    </div>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-[#E0D7C5]">
        <ul className="fixed z-20 flex min-h-screen flex-col items-center justify-end gap-8 border-r border-black px-3 py-8 text-2xl">
          <li
            key="Github"
            className="flex h-6 w-6 cursor-pointer items-center justify-center hover:text-[#4A4A4A]"
          >
            <a href="https://github.com/oweenen" target="_blank">
              <GithubIcon />
            </a>
          </li>
          <li
            key="LinkedIn"
            className="flex h-6 w-6 cursor-pointer items-center justify-center hover:text-[#4A4A4A]"
          >
            <LinkedInIcon />
          </li>
          <li
            key="Discord"
            className="flex h-6 w-6 cursor-pointer items-center justify-center hover:text-[#4A4A4A]"
          >
            <DiscordIcon />
          </li>
          <li
            key="Email"
            className="flex h-6 w-6 cursor-pointer items-center justify-center hover:text-[#4A4A4A]"
          >
            <EmailIcon />
          </li>
        </ul>
        <div className="fixed z-10 flex w-full flex-row items-center justify-end gap-12 border-b border-black bg-inherit px-12 py-2 text-2xl font-light">
          <span className="cursor-pointer hover:text-[#4A4A4A]">About</span>
          <span className="cursor-pointer hover:text-[#4A4A4A]">Skills</span>
          <span className="cursor-pointer hover:text-[#4A4A4A]">Projects</span>
          <span className="cursor-pointer hover:text-[#4A4A4A]">
            Experience
          </span>
        </div>
        <div className="flex min-h-screen flex-col items-start gap-24 py-60 pl-60">
          <div className="flex w-80 flex-col gap-6 justify-self-center">
            <span className="whitespace-nowrap text-5xl font-bold">
              Hi, I'm Owen
            </span>
            <div className="relative h-0">
              <PlusIcon className="absolute bottom-[-20px] left-[-35px] text-4xl" />
            </div>
            <span className="text-3xl">
              University Student <SchoolIcon className="inline" />
            </span>
            <p>
              I am currently in my junior year at The University of
              Massachusetts Lowell studying Computer Science with a focus on
              Data Science.
            </p>
            <span className="text-3xl">
              Web Developer <DevIcon className="inline" />
            </span>
            <p>
              I build full stack web applications about things I find
              interesting.
            </p>
          </div>
          <div className="flex flex-col gap-2">
            <span className="text-2xl">Languages</span>
            <div className="flex flex-row gap-3 border border-black bg-[#C9C9C2] p-3">
              <Skill id="javascript" icon={JavascriptIcon} />
              <Skill id="typescript" icon={TypescriptIcon} />
              <Skill id="html" icon={HtmlIcon} />
              <Skill id="css" icon={CssIcon} />
              <Skill id="python" icon={PythonIcon} />
              <Skill id="c" icon={CIcon} />
              <Skill id="cplusplus" icon={CPlusPlusIcon} />
              <Skill id="go" icon={GoIcon} />
              <Skill id="rust" icon={RustIcon} />
              <Skill id="sql" icon={SqlIcon} />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
